"""stenograf — accuracy-first local meeting transcription. Audio never touches disk."""

from importlib.metadata import PackageNotFoundError, version
from pathlib import Path

ASSETS = Path(__file__).parent / "assets"
"""Brand assets shipped in the wheel: ``icon.png`` (the window, Dock and
application-menu icon) and the frozen ``Stenograf.app`` bundle template
(:mod:`stenograf.shortcut`). Generated by ``native/appbundle/build.sh``."""

try:
    __version__ = version("stenograf")
except PackageNotFoundError:  # running from a source tree without installation
    __version__ = "0.0.0.dev0"
