"""The double-clickable launcher ``steno setup`` drops on each platform.

After the one-time setup nobody has to type a command again. What gets written
differs by platform, and everywhere by whether the desktop app is installed
(:func:`gui_installed`) — the double-click route opens the app when Qt is
there and the terminal launcher when it is not:

- **macOS with the ``gui`` extra**: ``~/Applications/Stenograf.app`` (Phase 8
  step 5) — a real app with an icon, copied verbatim from the frozen bundle in
  ``assets/``. See below; it is the only launcher with rules attached.
- **macOS without it**: ``~/Desktop/Stenograf.command``, which opens the
  terminal launcher in Terminal.app. An ``.app`` cannot host a TUI, and an app
  that opens an error dialog would be worse than the shortcut it replaced.
- **Linux**: an application-menu entry (a file *on* the GNOME desktop would
  need a manual "allow launching" step, the menu entry doesn't) — running
  ``--gui`` outside a terminal, or the TUI inside one.
- **Windows**: a Desktop ``Stenograf.cmd`` — ``steno`` is a console app, so a
  ``.lnk`` would open a console window anyway, and the batch wrapper is a plain
  text file this module can regenerate without COM. The app variant runs
  ``pythonw.exe`` through ``start``, so the console it does open belongs to the
  wrapper and closes immediately. A ``.lnk`` would avoid even that flash, but
  it needs COM (or a PowerShell detour) plus an ``.ico`` this project does not
  ship, and the obvious script wrappers that dodge COM are VBScript, which
  Windows is in the middle of removing.

The terminal launchers embed the absolute interpreter and run ``-m stenograf``:
a double-clicked launcher gets a login-shell PATH that may lack uv's shim
directory. Re-running ``steno setup`` regenerates them, self-healing the
embedded path after a reinstall. The Linux and Windows launchers are rewritten
in place, so installing or removing the extra converts the existing one rather
than leaving two entries named Stenograf that do different things.

**The app bundle is the exception to that self-healing, and it matters.** macOS
stores the microphone and system-audio grants against the cdhash of
``Contents/MacOS/Stenograf`` — no identifier, no anchor (measured, PLAN.md Phase
8 step 2) — so a bundle rewritten with a machine-specific path inside it would
be a different app to TCC on every install, and every change to it silently
revokes the grant of everyone who already answered the prompt. The bundle is
therefore copied byte-for-byte and never generated: the part that varies, the
command to launch, goes into :func:`launch_target_path` *outside* the bundle,
which the stub reads at every launch.

A locally *written* file carries no quarantine flag, so all of this opens
without Gatekeeper friction — unlike anything downloaded from a browser, which
macOS now hard-blocks unless it is notarized (tested on Tahoe; that is why
there is no downloadable double-click artifact yet).
"""

from __future__ import annotations

import os
import shutil
import sys
from pathlib import Path

from stenograf import ASSETS

BUNDLE_TEMPLATE = ASSETS / "Stenograf.app"
ICON = ASSETS / "icon.png"

DESKTOP_FILE_NAME = "stenograf"
"""Basename of the Linux desktop entry, and the app_id the window reports.

A desktop shell matches a running window back to the entry that launched it by
app_id (Wayland) or ``WM_CLASS`` (X11); without a match the window loses the
entry's icon and appears as a second, nameless "Stenograf" in the taskbar. Qt
takes both from ``QGuiApplication.setDesktopFileName``, which ``gui/app.py``
calls with *this* constant — shared rather than spelled twice, since two
strings that must be equal will otherwise drift.

Lowercase, like every app_id. The ``StartupWMClass`` written below is the X11
half, where Qt derives the class name from the application name and may
capitalize it; GNOME retries its lookup against a lowercased ``WM_CLASS``, so
the lowercase spelling is the one that matches both.
"""

_MACOS_COMMAND = """\
#!/bin/sh
# Stenograf launcher — regenerated by `steno setup`.
exec "{python}" -m stenograf
"""

_LAUNCH_TARGET = """\
# What Stenograf.app runs, one argument per line (blank lines and #-comments
# are ignored). Rewritten by `steno setup`.
#
# It lives out here because the app bundle itself must never change: macOS pins
# the app's microphone grant to the bundle's exact contents, so anything
# machine-specific — this path — has to stay outside it.
{command}
"""

_LINUX_DESKTOP = """\
[Desktop Entry]
# Stenograf launcher — regenerated by `steno setup`.
Type=Application
Name=Stenograf
Comment=Meeting transcription
Exec="{python}" -m stenograf{args}
Icon={icon}
Terminal={terminal}
Categories=AudioVideo;Audio;Utility;
"""

# Only the app gets this line: it is what a terminal-hosted TUI has no window
# to be matched against. See DESKTOP_FILE_NAME.
_LINUX_WM_CLASS = "StartupWMClass={name}\n"

# ASCII only: cmd.exe reads batch files in the OEM code page, not UTF-8.
_WINDOWS_CMD = """\
@echo off
rem Stenograf launcher - regenerated by `steno setup`.
"{python}" -m stenograf
rem A double-clicked window closes on exit; hold it open when steno crashed
rem so the error stays readable.
if errorlevel 1 pause
"""

# `start` rather than a plain call: the wrapper hands the app to the shell and
# exits, instead of leaving a console window open for the life of the meeting.
# The first quoted argument is the window title `start` insists on consuming.
_WINDOWS_GUI_CMD = """\
@echo off
rem Stenograf launcher - regenerated by `steno setup`.
start "Stenograf" "{python}" -m stenograf --gui
"""


def install_shortcut() -> Path | None:
    """Write this platform's launcher and return its path (``None`` if headless).

    The launcher follows the ``gui`` extra everywhere: with Qt installed it
    opens the desktop app, without it the terminal launcher (see the module
    docstring). On macOS this also writes :func:`launch_target_path`, which is
    what points the app at *this* installation of ``steno``.
    """
    gui = gui_installed()
    if sys.platform == "darwin":
        return _install_app() if gui else _install_command_file()
    if sys.platform.startswith("linux"):
        return _install_desktop_entry(gui=gui)
    if sys.platform == "win32":
        return _install_cmd_file(gui=gui)
    return None


def launch_target_path() -> Path:
    """The file naming the command ``Stenograf.app`` launches.

    Deliberately not under :func:`~stenograf.profiles.data_dir`, whose location
    ``$STENOGRAF_DATA`` can move: the app's launcher stub is started by launchd
    with no user environment, reads one hard-coded path and has no way to learn
    about an override. The two must agree, so both are fixed.
    """
    return Path.home() / "Library" / "Application Support" / "stenograf" / "launch-target"


def gui_installed() -> bool:
    """Is the ``gui`` extra present? Decides which launcher makes sense.

    Public because ``steno setup`` asks the same question to phrase its closing
    lines: a user without the extra is told how to get the app, and one with it
    is told where the app now is.
    """
    import importlib.util

    return importlib.util.find_spec("PySide6") is not None


def _install_desktop_entry(*, gui: bool) -> Path:
    """The Linux application-menu entry, pointed at the app or at the TUI.

    ``Terminal=`` is the whole difference in behaviour: the TUI needs a terminal
    emulator opened for it, and the app must not have one opened behind it.
    """
    apps = Path(os.environ.get("XDG_DATA_HOME", "~/.local/share")).expanduser() / "applications"
    apps.mkdir(parents=True, exist_ok=True)
    target = apps / f"{DESKTOP_FILE_NAME}.desktop"
    content = _LINUX_DESKTOP.format(
        python=sys.executable,
        args=" --gui" if gui else "",
        icon=ICON,
        terminal="false" if gui else "true",
    )
    if gui:
        content += _LINUX_WM_CLASS.format(name=DESKTOP_FILE_NAME)
    target.write_text(content, encoding="utf-8")
    return target


def _install_cmd_file(*, gui: bool) -> Path:
    """The Windows Desktop wrapper, pointed at the app or at the TUI.

    The two variants trade opposite things away. The terminal one keeps its
    console — that is where the TUI lives, and where a crash stays readable.
    The app one has no console to report into: ``start`` returns the moment the
    app is handed over, so a launch that fails (the extra uninstalled from under
    it, an import error) fails silently, and ``steno --gui`` from a terminal is
    what shows why.
    """
    target = _windows_desktop() / "Stenograf.cmd"
    target.parent.mkdir(parents=True, exist_ok=True)
    template = _WINDOWS_GUI_CMD if gui else _WINDOWS_CMD
    python = _windowed_python() if gui else sys.executable
    target.write_text(template.format(python=python), encoding="ascii")
    return target


def _windowed_python() -> str:
    """``pythonw.exe`` beside this interpreter — the console-less twin.

    Every CPython install and every venv ships both, so the fallback only covers
    a stripped or embedded interpreter, where a console window that stays open
    beats a launcher that starts nothing.
    """
    windowed = Path(sys.executable).with_name("pythonw.exe")
    return str(windowed) if windowed.is_file() else sys.executable


def _install_app() -> Path:
    """Put the frozen bundle in ``~/Applications`` and point it at this install.

    ``~/Applications`` rather than the Desktop: it is where a user-owned app
    belongs, and Spotlight and Launchpad index it. The grant does not care —
    TCC keys on the bundle's contents, not its path — so the app can be moved
    or dragged to the Dock afterwards.
    """
    target = Path.home() / "Applications" / "Stenograf.app"
    target.parent.mkdir(parents=True, exist_ok=True)

    path = launch_target_path()
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(_LAUNCH_TARGET.format(command="\n".join(_launch_command())), encoding="utf-8")

    if not _bundle_is_current(target):
        _replace_bundle(target)
    _retire_command_file()
    return target


def _launch_command() -> list[str]:
    """The argv the app should run: this installation's ``steno``, with ``--gui``.

    ``sys.executable``'s own directory first — a machine can hold several
    installs (a uv tool, a dev checkout), and setup should point the app at the
    one it is being run from rather than at whatever PATH resolves to.

    ``--gui`` is not optional here: the app has no terminal to host the Textual
    launcher in. The flag is also baked into the frozen stub as its fallback, so
    the CLI has to keep accepting it even after the GUI becomes the default.
    """
    console_script = Path(sys.executable).parent / "steno"
    if console_script.is_file():
        return [str(console_script), "--gui"]
    if (found := shutil.which("steno")) is not None:
        return [found, "--gui"]
    return [sys.executable, "-m", "stenograf", "--gui"]


def _bundle_is_current(target: Path) -> bool:
    """Is the installed bundle already the one we ship, byte for byte?

    Only the two sealed files are compared — the executable carries the cdhash,
    and the Info.plist and icon are hashed into it — which is enough to tell an
    up-to-date install from a stale one without walking the tree.
    """
    for relative in ("Contents/MacOS/Stenograf", "Contents/Info.plist"):
        installed = target / relative
        if not installed.is_file():
            return False
        if installed.read_bytes() != (BUNDLE_TEMPLATE / relative).read_bytes():
            return False
    return True


def _replace_bundle(target: Path) -> None:
    """Copy the template into place, staging it first.

    Staged and renamed rather than written over: a copy interrupted halfway
    would otherwise leave an app that launches into an error dialog. The one
    thing done to the copy is a ``chmod`` — wheels do not always preserve the
    executable bit, and file modes are not part of the signature, so this
    cannot disturb the cdhash.
    """
    staging = target.with_name(target.name + ".new")
    if staging.exists():
        shutil.rmtree(staging)
    shutil.copytree(BUNDLE_TEMPLATE, staging)
    (staging / "Contents" / "MacOS" / "Stenograf").chmod(0o755)
    if target.exists():
        shutil.rmtree(target)
    staging.rename(target)


def _command_file_path() -> Path:
    return Path.home() / "Desktop" / "Stenograf.command"


def _install_command_file() -> Path:
    """The pre-app macOS launcher: a Terminal.app shell script on the Desktop."""
    target = _command_file_path()
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(_MACOS_COMMAND.format(python=sys.executable), encoding="utf-8")
    target.chmod(0o755)
    return target


def _retire_command_file() -> None:
    """Remove the Desktop shortcut the app replaces — but only if we wrote it.

    Leaving it behind means two launchers with different behaviour (one opens a
    terminal, one opens the app). Anything that does not look like our own
    generated file is left alone; it is the user's Desktop.
    """
    legacy = _command_file_path()
    try:
        content = legacy.read_text(encoding="utf-8")
    except OSError:
        return
    if content.startswith("#!/bin/sh") and "-m stenograf" in content:
        legacy.unlink(missing_ok=True)


def _windows_desktop() -> Path:
    """The user's real Desktop folder, honoring shell-folder redirection.

    OneDrive's folder backup relocates the Desktop (``~/OneDrive/Desktop``) on
    a large share of Windows 11 machines, leaving ``~/Desktop`` an invisible
    decoy — the shell's User Shell Folders key knows where it really is.
    Falls back to ``~/Desktop`` when the key is unreadable.
    """
    fallback = Path.home() / "Desktop"
    if sys.platform != "win32":  # also lets the type checker use win32 stubs
        return fallback
    import winreg

    try:
        with winreg.OpenKey(
            winreg.HKEY_CURRENT_USER,
            r"Software\Microsoft\Windows\CurrentVersion\Explorer\User Shell Folders",
        ) as key:
            value, _ = winreg.QueryValueEx(key, "Desktop")
    except OSError:
        return fallback
    if not isinstance(value, str) or not value:
        return fallback
    # REG_EXPAND_SZ arrives unexpanded (typically "%USERPROFILE%\Desktop").
    return Path(os.path.expandvars(value))
