"""Double-clickable desktop launcher (PLAN.md §5, Phase 7 Task 6).

``steno setup`` drops a shortcut that opens the bare-``steno`` launcher TUI in
the platform's terminal, so after the one-time setup nobody has to type a
command again. The shortcut embeds the absolute interpreter and runs
``-m stenograf`` because a double-clicked launcher gets a login-shell PATH
that may lack uv's shim directory; re-running ``steno setup`` regenerates it,
which also self-heals the embedded path after a reinstall.

A locally *written* file carries no quarantine flag, so the launcher opens
without Gatekeeper friction — unlike anything downloaded from a browser,
which macOS now hard-blocks unless it is notarized (tested on Tahoe; that is
why there is no downloadable double-click artifact yet).
"""

from __future__ import annotations

import os
import sys
from pathlib import Path

_MACOS_COMMAND = """\
#!/bin/sh
# Stenograf launcher — regenerated by `steno setup`.
exec "{python}" -m stenograf
"""

_LINUX_DESKTOP = """\
[Desktop Entry]
# Stenograf launcher — regenerated by `steno setup`.
Type=Application
Name=Stenograf
Comment=Meeting transcription
Exec="{python}" -m stenograf
Terminal=true
Categories=AudioVideo;Audio;Utility;
"""

# ASCII only: cmd.exe reads batch files in the OEM code page, not UTF-8.
_WINDOWS_CMD = """\
@echo off
rem Stenograf launcher - regenerated by `steno setup`.
"{python}" -m stenograf
rem A double-clicked window closes on exit; hold it open when steno crashed
rem so the error stays readable.
if errorlevel 1 pause
"""


def install_shortcut() -> Path | None:
    """Write this platform's launcher and return its path.

    macOS: ``~/Desktop/Stenograf.command`` (double-click opens Terminal, which
    is also the app the setup TCC grants attach to). Linux: an application-menu
    entry under ``$XDG_DATA_HOME/applications`` — a file *on* the GNOME desktop
    would additionally need a manual "allow launching" step, the menu entry
    doesn't. Windows: a Desktop ``Stenograf.cmd`` — ``steno`` is a console app,
    so a ``.lnk`` would open a console window anyway, and the batch wrapper is
    a plain text file this function can regenerate without COM. Other
    platforms: returns ``None``.
    """
    if sys.platform == "darwin":
        target = Path.home() / "Desktop" / "Stenograf.command"
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(_MACOS_COMMAND.format(python=sys.executable), encoding="utf-8")
        target.chmod(0o755)
        return target
    if sys.platform.startswith("linux"):
        apps = Path(os.environ.get("XDG_DATA_HOME", "~/.local/share")).expanduser() / "applications"
        apps.mkdir(parents=True, exist_ok=True)
        target = apps / "stenograf.desktop"
        target.write_text(_LINUX_DESKTOP.format(python=sys.executable), encoding="utf-8")
        return target
    if sys.platform == "win32":
        target = _windows_desktop() / "Stenograf.cmd"
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(_WINDOWS_CMD.format(python=sys.executable), encoding="ascii")
        return target
    return None


def _windows_desktop() -> Path:
    """The user's real Desktop folder, honoring shell-folder redirection.

    OneDrive's folder backup relocates the Desktop (``~/OneDrive/Desktop``) on
    a large share of Windows 11 machines, leaving ``~/Desktop`` an invisible
    decoy — the shell's User Shell Folders key knows where it really is.
    Falls back to ``~/Desktop`` when the key is unreadable.
    """
    fallback = Path.home() / "Desktop"
    if sys.platform != "win32":  # also lets the type checker use win32 stubs
        return fallback
    import winreg

    try:
        with winreg.OpenKey(
            winreg.HKEY_CURRENT_USER,
            r"Software\Microsoft\Windows\CurrentVersion\Explorer\User Shell Folders",
        ) as key:
            value, _ = winreg.QueryValueEx(key, "Desktop")
    except OSError:
        return fallback
    if not isinstance(value, str) or not value:
        return fallback
    # REG_EXPAND_SZ arrives unexpanded (typically "%USERPROFILE%\Desktop").
    return Path(os.path.expandvars(value))
