"""The double-clickable launcher ``steno setup`` drops on each platform.

After the one-time setup nobody has to type a command again. What gets written
differs by platform, and on macOS by whether the desktop app is installed:

- **macOS with the ``gui`` extra**: ``~/Applications/Stenograf.app`` (Phase 8
  step 5) — a real app with an icon, copied verbatim from the frozen bundle in
  ``assets/``. See below; it is the only launcher with rules attached.
- **macOS without it**: ``~/Desktop/Stenograf.command``, which opens the
  terminal launcher in Terminal.app. An ``.app`` cannot host a TUI, and an app
  that opens an error dialog would be worse than the shortcut it replaced.
- **Linux**: an application-menu entry (a file *on* the GNOME desktop would
  need a manual "allow launching" step, the menu entry doesn't).
- **Windows**: a Desktop ``Stenograf.cmd`` — ``steno`` is a console app, so a
  ``.lnk`` would open a console window anyway, and the batch wrapper is a plain
  text file this module can regenerate without COM.

The terminal launchers embed the absolute interpreter and run ``-m stenograf``:
a double-clicked launcher gets a login-shell PATH that may lack uv's shim
directory. Re-running ``steno setup`` regenerates them, self-healing the
embedded path after a reinstall.

**The app bundle is the exception to that self-healing, and it matters.** macOS
stores the microphone and system-audio grants against the cdhash of
``Contents/MacOS/Stenograf`` — no identifier, no anchor (measured, PLAN.md Phase
8 step 2) — so a bundle rewritten with a machine-specific path inside it would
be a different app to TCC on every install, and every change to it silently
revokes the grant of everyone who already answered the prompt. The bundle is
therefore copied byte-for-byte and never generated: the part that varies, the
command to launch, goes into :func:`launch_target_path` *outside* the bundle,
which the stub reads at every launch.

A locally *written* file carries no quarantine flag, so all of this opens
without Gatekeeper friction — unlike anything downloaded from a browser, which
macOS now hard-blocks unless it is notarized (tested on Tahoe; that is why
there is no downloadable double-click artifact yet).
"""

from __future__ import annotations

import os
import shutil
import sys
from pathlib import Path

from stenograf import ASSETS

BUNDLE_TEMPLATE = ASSETS / "Stenograf.app"
ICON = ASSETS / "icon.png"

_MACOS_COMMAND = """\
#!/bin/sh
# Stenograf launcher — regenerated by `steno setup`.
exec "{python}" -m stenograf
"""

_LAUNCH_TARGET = """\
# What Stenograf.app runs, one argument per line (blank lines and #-comments
# are ignored). Rewritten by `steno setup`.
#
# It lives out here because the app bundle itself must never change: macOS pins
# the app's microphone grant to the bundle's exact contents, so anything
# machine-specific — this path — has to stay outside it.
{command}
"""

_LINUX_DESKTOP = """\
[Desktop Entry]
# Stenograf launcher — regenerated by `steno setup`.
Type=Application
Name=Stenograf
Comment=Meeting transcription
Exec="{python}" -m stenograf
Icon={icon}
Terminal=true
Categories=AudioVideo;Audio;Utility;
"""

# ASCII only: cmd.exe reads batch files in the OEM code page, not UTF-8.
_WINDOWS_CMD = """\
@echo off
rem Stenograf launcher - regenerated by `steno setup`.
"{python}" -m stenograf
rem A double-clicked window closes on exit; hold it open when steno crashed
rem so the error stays readable.
if errorlevel 1 pause
"""


def install_shortcut() -> Path | None:
    """Write this platform's launcher and return its path (``None`` if headless).

    On macOS this also writes :func:`launch_target_path`, which is what points
    the app at *this* installation of ``steno``.
    """
    if sys.platform == "darwin":
        return _install_app() if _qt_installed() else _install_command_file()
    if sys.platform.startswith("linux"):
        apps = Path(os.environ.get("XDG_DATA_HOME", "~/.local/share")).expanduser() / "applications"
        apps.mkdir(parents=True, exist_ok=True)
        target = apps / "stenograf.desktop"
        target.write_text(
            _LINUX_DESKTOP.format(python=sys.executable, icon=ICON), encoding="utf-8"
        )
        return target
    if sys.platform == "win32":
        target = _windows_desktop() / "Stenograf.cmd"
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(_WINDOWS_CMD.format(python=sys.executable), encoding="ascii")
        return target
    return None


def launch_target_path() -> Path:
    """The file naming the command ``Stenograf.app`` launches.

    Deliberately not under :func:`~stenograf.profiles.data_dir`, whose location
    ``$STENOGRAF_DATA`` can move: the app's launcher stub is started by launchd
    with no user environment, reads one hard-coded path and has no way to learn
    about an override. The two must agree, so both are fixed.
    """
    return Path.home() / "Library" / "Application Support" / "stenograf" / "launch-target"


def _qt_installed() -> bool:
    """Is the ``gui`` extra present? Decides which macOS launcher makes sense."""
    import importlib.util

    return importlib.util.find_spec("PySide6") is not None


def _install_app() -> Path:
    """Put the frozen bundle in ``~/Applications`` and point it at this install.

    ``~/Applications`` rather than the Desktop: it is where a user-owned app
    belongs, and Spotlight and Launchpad index it. The grant does not care —
    TCC keys on the bundle's contents, not its path — so the app can be moved
    or dragged to the Dock afterwards.
    """
    target = Path.home() / "Applications" / "Stenograf.app"
    target.parent.mkdir(parents=True, exist_ok=True)

    path = launch_target_path()
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(_LAUNCH_TARGET.format(command="\n".join(_launch_command())), encoding="utf-8")

    if not _bundle_is_current(target):
        _replace_bundle(target)
    _retire_command_file()
    return target


def _launch_command() -> list[str]:
    """The argv the app should run: this installation's ``steno``, with ``--gui``.

    ``sys.executable``'s own directory first — a machine can hold several
    installs (a uv tool, a dev checkout), and setup should point the app at the
    one it is being run from rather than at whatever PATH resolves to.

    ``--gui`` is not optional here: the app has no terminal to host the Textual
    launcher in. The flag is also baked into the frozen stub as its fallback, so
    the CLI has to keep accepting it even after the GUI becomes the default.
    """
    console_script = Path(sys.executable).parent / "steno"
    if console_script.is_file():
        return [str(console_script), "--gui"]
    if (found := shutil.which("steno")) is not None:
        return [found, "--gui"]
    return [sys.executable, "-m", "stenograf", "--gui"]


def _bundle_is_current(target: Path) -> bool:
    """Is the installed bundle already the one we ship, byte for byte?

    Only the two sealed files are compared — the executable carries the cdhash,
    and the Info.plist and icon are hashed into it — which is enough to tell an
    up-to-date install from a stale one without walking the tree.
    """
    for relative in ("Contents/MacOS/Stenograf", "Contents/Info.plist"):
        installed = target / relative
        if not installed.is_file():
            return False
        if installed.read_bytes() != (BUNDLE_TEMPLATE / relative).read_bytes():
            return False
    return True


def _replace_bundle(target: Path) -> None:
    """Copy the template into place, staging it first.

    Staged and renamed rather than written over: a copy interrupted halfway
    would otherwise leave an app that launches into an error dialog. The one
    thing done to the copy is a ``chmod`` — wheels do not always preserve the
    executable bit, and file modes are not part of the signature, so this
    cannot disturb the cdhash.
    """
    staging = target.with_name(target.name + ".new")
    if staging.exists():
        shutil.rmtree(staging)
    shutil.copytree(BUNDLE_TEMPLATE, staging)
    (staging / "Contents" / "MacOS" / "Stenograf").chmod(0o755)
    if target.exists():
        shutil.rmtree(target)
    staging.rename(target)


def _command_file_path() -> Path:
    return Path.home() / "Desktop" / "Stenograf.command"


def _install_command_file() -> Path:
    """The pre-app macOS launcher: a Terminal.app shell script on the Desktop."""
    target = _command_file_path()
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(_MACOS_COMMAND.format(python=sys.executable), encoding="utf-8")
    target.chmod(0o755)
    return target


def _retire_command_file() -> None:
    """Remove the Desktop shortcut the app replaces — but only if we wrote it.

    Leaving it behind means two launchers with different behaviour (one opens a
    terminal, one opens the app). Anything that does not look like our own
    generated file is left alone; it is the user's Desktop.
    """
    legacy = _command_file_path()
    try:
        content = legacy.read_text(encoding="utf-8")
    except OSError:
        return
    if content.startswith("#!/bin/sh") and "-m stenograf" in content:
        legacy.unlink(missing_ok=True)


def _windows_desktop() -> Path:
    """The user's real Desktop folder, honoring shell-folder redirection.

    OneDrive's folder backup relocates the Desktop (``~/OneDrive/Desktop``) on
    a large share of Windows 11 machines, leaving ``~/Desktop`` an invisible
    decoy — the shell's User Shell Folders key knows where it really is.
    Falls back to ``~/Desktop`` when the key is unreadable.
    """
    fallback = Path.home() / "Desktop"
    if sys.platform != "win32":  # also lets the type checker use win32 stubs
        return fallback
    import winreg

    try:
        with winreg.OpenKey(
            winreg.HKEY_CURRENT_USER,
            r"Software\Microsoft\Windows\CurrentVersion\Explorer\User Shell Folders",
        ) as key:
            value, _ = winreg.QueryValueEx(key, "Desktop")
    except OSError:
        return fallback
    if not isinstance(value, str) or not value:
        return fallback
    # REG_EXPAND_SZ arrives unexpanded (typically "%USERPROFILE%\Desktop").
    return Path(os.path.expandvars(value))
