from stenograf.notes import MeetingNotes, NotesProvenance

BODY = """\
We planned Q3.

Budget was the main topic.

## Decisions

- Ship in July

## Action items

- [ ] Draft the budget — **Anna** (due Friday) [2:05]
"""


def full_notes(warnings=()) -> MeetingNotes:
    return MeetingNotes(
        title="Q3 Planning",
        body=BODY,
        provenance=NotesProvenance(
            backend="command",
            model="claude",
            strategy="single-shot",
            language="de",
            warnings=warnings,
        ),
    )


def test_markdown_is_one_h1_plus_body_plus_provenance():
    md = full_notes().to_markdown()
    assert md.startswith("# Q3 Planning\n")
    assert md.count("\n# ") == 0  # exactly one H1 — the resolved title's
    assert "## Decisions" in md
    assert "- [ ] Draft the budget — **Anna** (due Friday) [2:05]" in md
    assert "command (claude), single-shot" in md  # provenance stamp
    assert "Warnings" not in md  # none to report


def test_markdown_records_warnings_in_the_footer():
    # The footer is the durable copy: a screen's status line is overwritten by
    # the next one, the note is not.
    md = full_notes(warnings=('section "## Open questions" is missing',)).to_markdown()
    assert '*Warnings: section "## Open questions" is missing.*' in md


def test_markdown_without_provenance_is_just_title_and_body():
    md = MeetingNotes(title="T", body="S").to_markdown()
    assert md == "# T\n\nS\n"
    assert "Generated by" not in md
