"""CLI tests for `steno notes`, the `--notes` flag, and the combined-note export."""

from pathlib import Path

import pytest
from click.testing import CliRunner
from conftest import write_wav
from test_cli import fake_load_backends

from stenograf import cli, loaders
from stenograf import notes as notes_pkg
from stenograf.config import Language, MeetingProfile
from stenograf.transcript import Transcript, TranscriptEntry

NOTES_MD = """\
# Quartalsplanung

Es wurde das Quartal geplant.

## Decisions

- Juli-Release

## Action items

- [ ] Budget entwerfen — **Anna**

## Highlights

- **Local-1**: Der Juli-Release steht.

## Open questions

- Q3-Einstellungen?
"""


@pytest.fixture(autouse=True)
def _isolate_data_dir(tmp_path, monkeypatch):
    from stenograf import output

    monkeypatch.setenv("STENOGRAF_DATA", str(tmp_path / "steno-data"))
    monkeypatch.setattr(output, "default_output_home", lambda: tmp_path / "meetings-home")
    monkeypatch.delenv("STENOGRAF_NOTES_BACKEND", raising=False)


class FakeBackend:
    name = "fake"
    model = "fake-model"
    max_input_chars = 48_000

    def __init__(self, available=True, response=NOTES_MD):
        self.available = available
        self.response = response

    def is_available(self):
        return self.available

    def complete(self, messages):
        return self.response


@pytest.fixture
def fake_backend(monkeypatch):
    backend = FakeBackend()
    monkeypatch.setattr(notes_pkg, "create_backend", lambda name, settings: backend)
    return backend


def write_transcript_json(path: Path, *, title=None) -> Transcript:
    transcript = Transcript(
        language=Language.GERMAN,
        profile=MeetingProfile(title=title),
        entries=[TranscriptEntry(speaker="Local-1", text="Hallo.", start=0.0, end=1.0)],
    )
    path.write_text(transcript.to_json(), encoding="utf-8")
    return transcript


def meeting_folder(tmp_path, name="meeting-20260710-143000", *, title=None) -> Path:
    """One finished meeting folder in the (isolated) output home."""
    meeting_dir = tmp_path / "meetings-home" / name
    meeting_dir.mkdir(parents=True)
    write_transcript_json(meeting_dir / "transcript.json", title=title)
    return meeting_dir


# ---- steno notes <path> --------------------------------------------------------


def test_notes_on_a_transcript_path_writes_the_sibling(tmp_path, fake_backend):
    path = tmp_path / "transcript.json"
    write_transcript_json(path)

    result = CliRunner().invoke(cli.main, ["notes", str(path)])

    assert result.exit_code == 0, result.output
    md = (tmp_path / "transcript.notes.md").read_text(encoding="utf-8")
    assert md.startswith("# Quartalsplanung")
    # Provenance is stamped in the note's own footer — the durable copy.
    assert "Generated by stenograf notes — fake (fake-model), single-shot." in md
    assert not (tmp_path / "transcript.notes.json").exists()  # no JSON sibling anymore


def test_notes_regeneration_unlinks_a_stale_json_sibling(tmp_path, fake_backend):
    # A meeting summarized before the markdown change keeps a .notes.json; a
    # regeneration must not leave it disagreeing with the fresh markdown.
    path = tmp_path / "transcript.json"
    write_transcript_json(path)
    stale = tmp_path / "transcript.notes.json"
    stale.write_text('{"title": "old"}', encoding="utf-8")

    result = CliRunner().invoke(cli.main, ["notes", str(path)])

    assert result.exit_code == 0, result.output
    assert not stale.exists()


def test_notes_validation_warnings_reach_the_screen(tmp_path, monkeypatch):
    import stenograf.notes as notes_pkg_local

    incomplete = NOTES_MD[: NOTES_MD.index("## Open questions")]
    monkeypatch.setattr(
        notes_pkg_local, "create_backend", lambda name, settings: FakeBackend(response=incomplete)
    )
    path = tmp_path / "transcript.json"
    write_transcript_json(path)

    result = CliRunner().invoke(cli.main, ["notes", str(path)])

    assert result.exit_code == 0, result.output  # warnings are not failures
    assert 'notes warning: section "## Open questions" is missing' in result.output
    md = (tmp_path / "transcript.notes.md").read_text(encoding="utf-8")
    assert "Warnings:" in md  # and the footer keeps the durable copy


def test_notes_on_a_flat_layout_transcript_names_siblings_after_it(tmp_path, fake_backend):
    path = tmp_path / "standup.transcript.json"
    write_transcript_json(path)

    result = CliRunner().invoke(cli.main, ["notes", str(path)])

    assert result.exit_code == 0, result.output
    assert (tmp_path / "standup.transcript.notes.md").exists()


def test_notes_on_garbage_json_fails_cleanly(tmp_path, fake_backend):
    path = tmp_path / "transcript.json"
    path.write_text("not json", encoding="utf-8")

    result = CliRunner().invoke(cli.main, ["notes", str(path)])

    assert result.exit_code != 0
    assert "not a readable transcript" in result.output


# ---- steno notes <folder> / --last ----------------------------------------------


def test_notes_on_a_meeting_folder_uses_its_transcript(tmp_path, fake_backend):
    meeting_dir = meeting_folder(tmp_path)

    result = CliRunner().invoke(cli.main, ["notes", str(meeting_dir)])

    assert result.exit_code == 0, result.output
    assert (meeting_dir / "transcript.notes.md").exists()


def test_notes_on_a_folder_without_a_transcript_errors(tmp_path, fake_backend):
    empty = tmp_path / "meetings-home" / "meeting-20260710-143000"
    empty.mkdir(parents=True)

    result = CliRunner().invoke(cli.main, ["notes", str(empty)])

    assert result.exit_code != 0
    assert "no transcript.json" in result.output


def test_notes_last_picks_the_newest_meeting_folder(tmp_path, fake_backend):
    meeting_folder(tmp_path, "meeting-20260709-090000")
    newest = meeting_folder(tmp_path, "meeting-20260710-143000")
    # Newer folder name, but no transcript.json (a crashed run) — skipped.
    (tmp_path / "meetings-home" / "meeting-20260711-080000").mkdir()

    result = CliRunner().invoke(cli.main, ["notes", "--last"])

    assert result.exit_code == 0, result.output
    assert str(newest) in result.output  # says which meeting it picked
    assert (newest / "transcript.notes.md").exists()


def test_notes_last_with_an_empty_home_fails_with_guidance(tmp_path, fake_backend):
    result = CliRunner().invoke(cli.main, ["notes", "--last"])
    assert result.exit_code != 0
    assert "no finished meeting" in result.output


def test_notes_requires_a_path_or_last_but_not_both(tmp_path, fake_backend):
    assert CliRunner().invoke(cli.main, ["notes"]).exit_code != 0
    meeting_dir = meeting_folder(tmp_path)
    result = CliRunner().invoke(cli.main, ["notes", str(meeting_dir), "--last"])
    assert result.exit_code != 0
    assert "not both" in result.output


def test_notes_backend_down_exits_nonzero_and_writes_nothing(tmp_path, monkeypatch):
    monkeypatch.setattr(
        notes_pkg, "create_backend", lambda name, settings: FakeBackend(available=False)
    )
    path = tmp_path / "transcript.json"
    write_transcript_json(path)

    result = CliRunner().invoke(cli.main, ["notes", str(path)])

    assert result.exit_code != 0
    assert not (tmp_path / "transcript.notes.md").exists()


def test_notes_reports_a_bug_as_a_traceback_not_a_clean_error(tmp_path, monkeypatch):
    # Documented failure modes (backend down, bad settings) become clean CLI
    # errors; a programming bug must keep its traceback, or an AttributeError
    # reads like "Ollama down" and never gets reported.
    def buggy(*args, **kwargs):
        raise AttributeError("'NoneType' object has no attribute 'entries'")

    monkeypatch.setattr(cli.notes, "_generate_and_write_notes", buggy)
    path = tmp_path / "transcript.json"
    write_transcript_json(path)

    result = CliRunner().invoke(cli.main, ["notes", str(path)])

    assert result.exit_code != 0
    assert isinstance(result.exception, AttributeError)


# ---- export --------------------------------------------------------------------


def test_notes_export_dir_writes_combined_note(tmp_path, fake_backend):
    # The export date comes from the folder name, which encodes the start time.
    meeting_dir = meeting_folder(tmp_path)
    vault = tmp_path / "vault" / "Meetings"

    result = CliRunner().invoke(cli.main, ["notes", str(meeting_dir), "--export-dir", str(vault)])

    assert result.exit_code == 0, result.output
    exported = vault / "2026-07-10 – Quartalsplanung.md"
    assert exported.exists()
    text = exported.read_text(encoding="utf-8")
    assert text.startswith("---\n")  # frontmatter
    assert "> [!quote]- Transcript" in text


def test_notes_export_defaults_from_settings_and_no_export_disables(tmp_path, fake_backend):
    import os

    vault = tmp_path / "vault"
    settings = Path(os.environ["STENOGRAF_DATA"]) / "settings.toml"
    settings.parent.mkdir(parents=True, exist_ok=True)
    # as_posix(): a raw Windows path in a TOML basic string is invalid (\U…).
    settings.write_text(f'[notes.export]\ndir = "{vault.as_posix()}"\n', encoding="utf-8")
    path = tmp_path / "transcript.json"
    write_transcript_json(path)

    result = CliRunner().invoke(cli.main, ["notes", str(path)])
    assert result.exit_code == 0, result.output
    assert list(vault.glob("*.md")), "settings-configured export dir was not used"

    result = CliRunner().invoke(cli.main, ["notes", str(path), "--no-export"])
    assert result.exit_code == 0, result.output
    assert len(list(vault.glob("*.md"))) == 1  # unchanged — export skipped


# ---- --notes flag on transcribe -------------------------------------------------


def test_transcribe_with_notes_flag_writes_notes(tmp_path, monkeypatch, fake_backend):
    monkeypatch.setattr(loaders, "load_backends", fake_load_backends)
    audio = tmp_path / "meeting.wav"
    write_wav(audio)

    result = CliRunner().invoke(
        cli.main, ["transcribe", str(audio), "--out", str(tmp_path), "--notes"]
    )

    assert result.exit_code == 0, result.output
    assert (tmp_path / "transcript.notes.md").exists()
    assert "notes: wrote" in result.output


def test_settings_notes_auto_generates_notes_without_the_flag(tmp_path, monkeypatch, fake_backend):
    # [notes] auto = true is the standing "always summarize" choice: no --notes.
    import os

    settings = Path(os.environ["STENOGRAF_DATA"]) / "settings.toml"
    settings.parent.mkdir(parents=True, exist_ok=True)
    settings.write_text("[notes]\nauto = true\n", encoding="utf-8")
    monkeypatch.setattr(loaders, "load_backends", fake_load_backends)
    audio = tmp_path / "meeting.wav"
    write_wav(audio)

    result = CliRunner().invoke(cli.main, ["transcribe", str(audio), "--out", str(tmp_path)])

    assert result.exit_code == 0, result.output
    assert (tmp_path / "transcript.notes.md").exists()


def test_no_notes_beats_settings_notes_auto(tmp_path, monkeypatch):
    # The per-run flag wins outright — auto = true still yields to --no-notes.
    import os

    def explode(name, settings):
        raise AssertionError("--no-notes was given; no backend may be created")

    settings = Path(os.environ["STENOGRAF_DATA"]) / "settings.toml"
    settings.parent.mkdir(parents=True, exist_ok=True)
    settings.write_text("[notes]\nauto = true\n", encoding="utf-8")
    monkeypatch.setattr(loaders, "load_backends", fake_load_backends)
    monkeypatch.setattr(notes_pkg, "create_backend", explode)
    audio = tmp_path / "meeting.wav"
    write_wav(audio)

    result = CliRunner().invoke(
        cli.main, ["transcribe", str(audio), "--out", str(tmp_path), "--no-notes"]
    )

    assert result.exit_code == 0, result.output
    assert not (tmp_path / "transcript.notes.md").exists()


def test_transcribe_notes_failure_is_nonfatal(tmp_path, monkeypatch):
    monkeypatch.setattr(loaders, "load_backends", fake_load_backends)
    monkeypatch.setattr(
        notes_pkg, "create_backend", lambda name, settings: FakeBackend(available=False)
    )
    audio = tmp_path / "meeting.wav"
    write_wav(audio)

    result = CliRunner().invoke(
        cli.main, ["transcribe", str(audio), "--out", str(tmp_path), "--notes"]
    )

    assert result.exit_code == 0, result.output  # transcript stands; run succeeds
    assert (tmp_path / "transcript.md").exists()
    assert not (tmp_path / "transcript.notes.md").exists()
    assert "notes failed" in result.output
    assert "steno notes" in result.output  # retry guidance


def test_transcribe_per_run_notes_trio_reaches_the_backend(tmp_path, monkeypatch):
    # --notes-backend/--notes-model/--instructions steer only this run's notes
    # step — the live-meeting/batch equivalent of `steno notes --backend` etc.
    monkeypatch.setattr(loaders, "load_backends", fake_load_backends)
    seen = {}

    class Recording(FakeBackend):
        def complete(self, messages):
            seen["messages"] = messages
            return self.response

    def record_create(name, settings):
        seen["name"] = name
        seen["settings"] = settings
        return Recording()

    monkeypatch.setattr(notes_pkg, "create_backend", record_create)
    style = tmp_path / "style.md"
    style.write_text("Immer Du-Form verwenden.", encoding="utf-8")
    audio = tmp_path / "meeting.wav"
    write_wav(audio)

    result = CliRunner().invoke(
        cli.main,
        [
            "transcribe",
            str(audio),
            "--out",
            str(tmp_path),
            "--notes",
            "--notes-backend",
            "command",
            "--notes-model",
            "claude",
            "--instructions",
            str(style),
        ],
    )

    assert result.exit_code == 0, result.output
    assert seen["name"] == "command"
    assert seen["settings"].model == "claude"
    assert "Immer Du-Form verwenden." in seen["messages"][0]["content"]


def test_notes_instructions_flag_replaces_the_settings_file(tmp_path, monkeypatch):
    # The per-run file replaces the standing one — trying a different style
    # must not stack the two.
    import os

    standing = tmp_path / "standing.md"
    standing.write_text("Standing style.", encoding="utf-8")
    settings = Path(os.environ["STENOGRAF_DATA"]) / "settings.toml"
    settings.parent.mkdir(parents=True, exist_ok=True)
    settings.write_text(f'[notes]\ninstructions = "{standing.as_posix()}"\n', encoding="utf-8")
    seen = {}

    class Recording(FakeBackend):
        def complete(self, messages):
            seen["messages"] = messages
            return self.response

    monkeypatch.setattr(notes_pkg, "create_backend", lambda name, settings: Recording())
    path = tmp_path / "transcript.json"
    write_transcript_json(path)
    per_run = tmp_path / "per-run.md"
    per_run.write_text("Per-run style.", encoding="utf-8")

    result = CliRunner().invoke(cli.main, ["notes", str(path), "--instructions", str(per_run)])

    assert result.exit_code == 0, result.output
    system = seen["messages"][0]["content"]
    assert "Per-run style." in system
    assert "Standing style." not in system


def test_transcribe_without_notes_flag_never_touches_a_backend(tmp_path, monkeypatch):
    def explode(name, settings):
        raise AssertionError("--notes was not given; no backend may be created")

    monkeypatch.setattr(loaders, "load_backends", fake_load_backends)
    monkeypatch.setattr(notes_pkg, "create_backend", explode)
    audio = tmp_path / "meeting.wav"
    write_wav(audio)

    result = CliRunner().invoke(cli.main, ["transcribe", str(audio), "--out", str(tmp_path)])

    assert result.exit_code == 0, result.output


# ---- meeting presets (--preset) --------------------------------------------------


CUSTOM_TEMPLATE = """\
# <Titel der Besprechung>

<Zusammenfassung>

## Beschlüsse

- <ein Beschluss pro Punkt>

## Offene Punkte

- <offener Punkt>
"""

GERMAN_MD = """\
# Controlling-Runde Juli

Es wurde das Budget besprochen.

## Beschlüsse

- Juli-Release freigegeben

## Offene Punkte

- Q3-Planung?
"""


def _write_preset_settings(tmp_path, template_path) -> None:
    import os

    settings = Path(os.environ["STENOGRAF_DATA"]) / "settings.toml"
    settings.parent.mkdir(parents=True, exist_ok=True)
    settings.write_text(
        f"""
[notes]
backend = "command"
model = "claude-opus-4-8"
command = ["claude", "-p"]

[meetings.controlling]
title = "Controlling-Runde"
language = "de"
template = "{template_path.as_posix()}"

[meetings.controlling.notes]
backend = "mlx"

[meetings.controlling.vocab]
attendees = ["Anja Preset"]
""",
        encoding="utf-8",
    )


def test_notes_preset_selects_backend_template_and_validates_against_it(tmp_path, monkeypatch):
    template_path = tmp_path / "controlling.md"
    template_path.write_text(CUSTOM_TEMPLATE, encoding="utf-8")
    _write_preset_settings(tmp_path, template_path)
    seen = {}

    class Recording(FakeBackend):
        def complete(self, messages):
            seen["messages"] = messages
            return self.response

    def record_create(name, settings):
        seen["name"] = name
        seen["settings"] = settings
        return Recording(response=GERMAN_MD)

    monkeypatch.setattr(notes_pkg, "create_backend", record_create)
    path = tmp_path / "transcript.json"
    write_transcript_json(path)

    result = CliRunner().invoke(cli.main, ["notes", str(path), "--preset", "controlling"])

    assert result.exit_code == 0, result.output
    assert "preset: controlling" in result.output  # echo-on-use
    # The preset's backend is passed explicitly (beats env), with the standing
    # model dropped (the pair rule — it was written for the command backend).
    assert seen["name"] == "mlx"
    assert seen["settings"].model is None
    # The preset's template rides last in the prompt and is what validation
    # matched GERMAN_MD against — German headings, zero warnings.
    assert "## Beschlüsse" in seen["messages"][-1]["content"]
    assert "notes warning" not in result.output
    md = (tmp_path / "transcript.notes.md").read_text(encoding="utf-8")
    assert "## Beschlüsse" in md


def test_notes_explicit_backend_flag_beats_the_preset(tmp_path, monkeypatch):
    template_path = tmp_path / "controlling.md"
    template_path.write_text(CUSTOM_TEMPLATE, encoding="utf-8")
    _write_preset_settings(tmp_path, template_path)
    seen = {}

    def record_create(name, settings):
        seen["name"] = name
        return FakeBackend(response=GERMAN_MD)

    monkeypatch.setattr(notes_pkg, "create_backend", record_create)
    path = tmp_path / "transcript.json"
    write_transcript_json(path)

    result = CliRunner().invoke(
        cli.main, ["notes", str(path), "--preset", "controlling", "--backend", "command"]
    )

    assert result.exit_code == 0, result.output
    assert seen["name"] == "command"


def test_notes_unknown_preset_fails_before_any_work(tmp_path, monkeypatch):
    def explode(name, settings):
        raise AssertionError("no backend may be created for an unknown preset")

    monkeypatch.setattr(notes_pkg, "create_backend", explode)
    path = tmp_path / "transcript.json"
    write_transcript_json(path)

    result = CliRunner().invoke(cli.main, ["notes", str(path), "--preset", "nope"])

    assert result.exit_code != 0
    assert "unknown meeting preset" in result.output


def test_transcribe_preset_stamps_title_language_and_vocab(tmp_path, monkeypatch):
    template_path = tmp_path / "controlling.md"
    template_path.write_text(CUSTOM_TEMPLATE, encoding="utf-8")
    _write_preset_settings(tmp_path, template_path)
    monkeypatch.setattr(loaders, "load_backends", fake_load_backends)
    audio = tmp_path / "meeting.wav"
    write_wav(audio)

    result = CliRunner().invoke(
        cli.main, ["transcribe", str(audio), "--out", str(tmp_path), "--preset", "controlling"]
    )

    assert result.exit_code == 0, result.output
    import json

    profile = json.loads((tmp_path / "transcript.json").read_text(encoding="utf-8"))["profile"]
    assert profile["title"] == "Controlling-Runde"
    assert profile["language"] == "de"
    assert "Anja Preset" in profile["attendee_names"]


def test_presets_command_lists_names_and_facts(tmp_path):
    template_path = tmp_path / "controlling.md"
    template_path.write_text(CUSTOM_TEMPLATE, encoding="utf-8")
    _write_preset_settings(tmp_path, template_path)

    result = CliRunner().invoke(cli.main, ["presets"])

    assert result.exit_code == 0, result.output
    assert "controlling" in result.output
    assert 'title "Controlling-Runde"' in result.output
    assert "notes via mlx" in result.output
    assert "template controlling.md" in result.output


def test_presets_command_with_none_defined_points_at_settings(tmp_path):
    result = CliRunner().invoke(cli.main, ["presets"])
    assert result.exit_code == 0, result.output
    assert "no meeting presets" in result.output


def test_command_backend_is_positioned_in_the_meeting_dir(tmp_path, monkeypatch):
    # The agentic contract: the notes command runs with the meeting folder as
    # cwd and the position in its environment — fetching context is its job.
    positions = []

    class Positionable(FakeBackend):
        def set_position(self, meeting_dir, output_home):
            positions.append((meeting_dir, output_home))

    monkeypatch.setattr(notes_pkg, "create_backend", lambda name, settings: Positionable())
    meeting_dir = meeting_folder(tmp_path)

    result = CliRunner().invoke(cli.main, ["notes", str(meeting_dir)])

    assert result.exit_code == 0, result.output
    assert positions == [(meeting_dir, meeting_dir.parent)]


# ---- Ctrl-C during the notes tail ------------------------------------------------


def test_one_interrupt_lets_notes_finish_and_a_second_skips_them(tmp_path, monkeypatch, capsys):
    # The retired TUI joined the notes tail on quit, so a stray Ctrl-C never
    # killed a half-done notes run; the plain CLI runs the tail on the main
    # thread, where the default handler would. The middle path: the first
    # Ctrl-C announces and lets generation finish, the second skips it —
    # non-fatally, because the transcript is already on disk.
    import signal
    from datetime import datetime

    from stenograf.cli import notes as notes_mod

    transcript = write_transcript_json(tmp_path / "transcript.json")
    before = signal.getsignal(signal.SIGINT)
    survived = []

    def interrupted_generation(*args, **kwargs):
        signal.raise_signal(signal.SIGINT)  # first: warned, generation goes on
        survived.append(True)
        signal.raise_signal(signal.SIGINT)  # second: skip
        raise AssertionError("unreachable — the second interrupt must raise")

    monkeypatch.setattr(notes_mod, "_generate_and_write_notes", interrupted_generation)

    notes_mod._notes_after_run(
        transcript, tmp_path, "transcript", created_at=datetime.now(), notes_settings=None
    )

    err = capsys.readouterr().err
    assert survived == [True]
    assert "Ctrl-C again to skip" in err
    assert "notes skipped" in err
    assert f"steno notes {tmp_path}" in err  # the regeneration pointer
    assert signal.getsignal(signal.SIGINT) is before  # the handler is restored
