from stenograf.notes import (
    ActionItem,
    MeetingNotes,
    NotesProvenance,
    SpeakerHighlight,
)


def full_notes() -> MeetingNotes:
    return MeetingNotes(
        title="Q3 Planning",
        summary="We planned Q3.\n\nBudget was the main topic.",
        decisions=("Ship in July", "Drop the legacy exporter"),
        action_items=(
            ActionItem(task="Draft the budget", owner="Anna", due="Friday", timestamp=125.0),
            ActionItem(task="Book the offsite"),
        ),
        highlights=(SpeakerHighlight(speaker="Remote-1", highlight="Revenue is up 12%"),),
        open_questions=("Do we hire in Q3?",),
        provenance=NotesProvenance(
            backend="command", model="claude", strategy="single-shot", language="de"
        ),
    )


def test_json_round_trip():
    notes = full_notes()
    assert MeetingNotes.from_json(notes.to_json()) == notes


def test_json_round_trip_minimal():
    notes = MeetingNotes(title="T", summary="S")
    assert MeetingNotes.from_json(notes.to_json()) == notes


def test_from_json_tolerates_missing_optional_keys():
    notes = MeetingNotes.from_json('{"title": "T", "summary": "S"}')
    assert notes.title == "T"
    assert notes.action_items == ()
    assert notes.provenance is None


def test_list_input_normalized_to_tuples():
    notes = MeetingNotes(title="T", summary="S", decisions=["a", "b"])
    assert notes.decisions == ("a", "b")


def test_markdown_renders_all_sections():
    md = full_notes().to_markdown()
    assert md.startswith("# Q3 Planning\n")
    assert "## Decisions" in md
    assert "- Ship in July" in md
    assert "- [ ] Draft the budget — **Anna** (due Friday) [2:05]" in md
    assert "- [ ] Book the offsite" in md
    assert "**Remote-1**: Revenue is up 12%" in md
    assert "## Open questions" in md
    assert "command (claude), single-shot" in md  # provenance stamp


def test_markdown_omits_empty_sections():
    md = MeetingNotes(title="T", summary="S").to_markdown()
    assert "## Decisions" not in md
    assert "## Action items" not in md
    assert "Generated by" not in md
