"""Notes data model — the note a notes backend produces.

Kept apart from :class:`~stenograf.transcript.Transcript` on purpose: notes
are derivative, regenerable output, written as a sibling ``.notes.md`` file so
the transcript schema stays pure. The body is markdown the model wrote against
the template (:mod:`.template`) — there is no field-level structure to
round-trip, so there is no JSON form.
"""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class NotesProvenance:
    """Which backend produced these notes, and how — stamped so a note is never
    mistaken for human writing and a regeneration can reproduce the setup."""

    backend: str
    model: str | None
    strategy: str
    """``single-shot`` or ``map-reduce`` (long meetings summarized in chunks)."""
    language: str | None
    """Language the notes were requested in (the transcript's), or ``None``."""
    warnings: tuple[str, ...] = ()
    """Validation warnings (missing template headings, empty sections, a
    fallback title). Recorded here so the evidence survives the screen — a
    status line is overwritten by the next one; the note is not."""

    def __post_init__(self) -> None:
        object.__setattr__(self, "warnings", tuple(self.warnings))


@dataclass(frozen=True)
class MeetingNotes:
    title: str
    """LLM-derived when the meeting had none — flows into the combined-note
    export filename."""
    body: str
    """The note as markdown, headings per the template, without the H1 (the
    renderers emit exactly one H1 from :attr:`title`)."""
    provenance: NotesProvenance | None = None

    def to_markdown(self) -> str:
        lines = [f"# {self.title}", "", self.body.rstrip()]
        if self.provenance is not None:
            p = self.provenance
            model = f" ({p.model})" if p.model else ""
            lines += ["", f"*Generated by stenograf notes — {p.backend}{model}, {p.strategy}.*"]
            if p.warnings:
                lines.append(f"*Warnings: {'; '.join(p.warnings)}.*")
        return "\n".join(lines) + "\n"
