"""Rasterize icon.svg into ``src/stenograf/assets/icon.ico`` — the Windows icon.

Run it directly, and **never from build.sh**::

    uv run --extra gui python native/appbundle/render_ico.py

Those are two separate rules. The SVG beside this file is the app's artwork on
every platform, which is the only reason a Windows tool lives in a directory
named for the macOS bundle. But `build.sh` rebuilds and re-signs the frozen
`.app`, and every rebuild silently revokes the microphone grant of everyone who
already answered the prompt (README.md). Nothing on Windows is pinned to a
launcher's bytes — a `.lnk` is regenerated by `steno setup` at will — so the
`.ico` is rendered on demand and committed like `icon.png`, with no rule
attached to it whatsoever.

Every size is rendered from the vector rather than downscaled from one big
bitmap, for the reason `render_icon.py` gives: at 16 px the waveform's rounded
caps turn to mush when they are resampled, and 16 px is the size the taskbar
and the title bar use. Qt does the rendering because PySide6 is already the
GUI's dependency — no ImageMagick, no Pillow. Keep icon.svg inside SVG Tiny 1.2
(no filters, no CSS); that is all Qt's renderer implements.

The container is assembled here instead of being handed to Qt's ICO writer,
which saves one image: an `.ico` is a *directory* of independent images, and
picking the one rendered for the size it wants is the entire point of handing
Windows the format at all.
"""

from __future__ import annotations

import os
import struct
import sys
from pathlib import Path

os.environ.setdefault("QT_QPA_PLATFORM", "offscreen")

from PySide6.QtCore import QBuffer, QIODevice, QRectF  # noqa: E402
from PySide6.QtGui import QGuiApplication, QImage, QPainter  # noqa: E402
from PySide6.QtSvg import QSvgRenderer  # noqa: E402

SIZES = (16, 24, 32, 48, 64, 128, 256)
"""What Windows actually asks for, smallest first.

16 (title bar, taskbar at 100 %), 24 (taskbar at 150 % — this project's own
notebook), 32 (Alt-Tab, small shell icons), 48 (the shell's default "medium"),
64, 128 and 256 (large tiles, the file dialog's extra-large view, and anything
scaled beyond 200 %). Windows picks by nearest-not-smaller and downsamples what
it gets, so the gaps cost sharpness rather than correctness.
"""

PNG_ENTRY_FROM = 256
"""At and above this size an entry is stored as PNG, below it as a BMP.

Vista's addition to the format, and the reason a 256 px icon costs ~15 KiB
rather than 256 KiB. The cut sits at 256 because that is where every writer of
this format puts it — a small PNG entry is read fine by modern Windows, but the
convention costs nothing to keep and the old readers are the ones that break.
"""


def _render(renderer: QSvgRenderer, pixels: int) -> QImage:
    image = QImage(pixels, pixels, QImage.Format.Format_ARGB32_Premultiplied)
    image.fill(0)  # transparent: the squircle, not the canvas, is the icon
    painter = QPainter(image)
    painter.setRenderHint(QPainter.RenderHint.Antialiasing)
    renderer.render(painter, QRectF(0, 0, pixels, pixels))
    painter.end()
    # Painting wants premultiplied alpha; the container stores straight alpha,
    # and skipping this leaves every antialiased edge darkened toward black.
    return image.convertToFormat(QImage.Format.Format_ARGB32)


def _png(image: QImage) -> bytes:
    buffer = QBuffer()
    buffer.open(QIODevice.OpenModeFlag.WriteOnly)
    if not image.save(buffer, "PNG"):
        raise SystemExit(f"could not PNG-encode the {image.width()} px entry")
    return bytes(buffer.data())


def _dib(image: QImage) -> bytes:
    """One classic entry: a BITMAPINFOHEADER, BGRA rows bottom-up, then a mask.

    Two details the format inherited from BMP and never dropped. The header
    claims **double the height**, because the pixels are followed by a 1-bit AND
    mask of the same dimensions; it is vestigial for a 32-bit image whose alpha
    channel already says what is transparent, but a reader that finds it missing
    reads the next entry's bytes as mask. And the rows run **bottom-up**, which
    is why this cannot simply be a memcpy of the QImage.
    """
    width, height = image.width(), image.height()
    stride = image.bytesPerLine()
    pixels = bytes(image.constBits())
    # Format_ARGB32 is 0xAARRGGBB in a machine word, i.e. B,G,R,A in memory on
    # little-endian — already the byte order a 32-bit DIB wants.
    rows = [pixels[y * stride : y * stride + width * 4] for y in reversed(range(height))]
    mask_stride = ((width + 31) // 32) * 4  # 1 bit per pixel, rows padded to 4 bytes
    mask = b"\x00" * (mask_stride * height)
    header = struct.pack(
        "<IiiHHIIiiII",
        40,  # biSize
        width,
        height * 2,  # biHeight — pixels plus the AND mask, see above
        1,  # biPlanes
        32,  # biBitCount
        0,  # biCompression = BI_RGB
        width * 4 * height + len(mask),  # biSizeImage
        0,  # biXPelsPerMeter
        0,  # biYPelsPerMeter
        0,  # biClrUsed
        0,  # biClrImportant
    )
    return b"".join([header, *rows, mask])


def _ico(images: list[QImage]) -> bytes:
    """Pack rendered images into one ICONDIR + ICONDIRENTRY[] + payloads file."""
    entries, payloads = [], []
    offset = 6 + 16 * len(images)  # past the directory, where the first image starts
    for image in images:
        size = image.width()
        payload = _png(image) if size >= PNG_ENTRY_FROM else _dib(image)
        entries.append(
            struct.pack(
                "<BBBBHHII",
                size & 0xFF,  # width: one byte, so the format spells 256 as 0
                size & 0xFF,  # height, likewise
                0,  # bColorCount — 0 for anything truecolor
                0,  # bReserved
                1,  # wPlanes
                32,  # wBitCount
                len(payload),
                offset,
            )
        )
        payloads.append(payload)
        offset += len(payload)
    directory = struct.pack("<HHH", 0, 1, len(images))  # reserved, type 1 = icon, count
    return b"".join([directory, *entries, *payloads])


def main(source: Path, target: Path) -> None:
    QGuiApplication(sys.argv)  # QImage painting needs an application object
    renderer = QSvgRenderer(str(source))
    if not renderer.isValid():
        raise SystemExit(f"{source} is not valid SVG (Qt's parser rejects it)")

    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_bytes(_ico([_render(renderer, size) for size in SIZES]))
    print(f"wrote {target} — {len(SIZES)} sizes, {target.stat().st_size} bytes")


if __name__ == "__main__":
    here = Path(__file__).resolve().parent
    repository = here.parent.parent
    main(
        Path(sys.argv[1]) if len(sys.argv) > 1 else here / "icon.svg",
        Path(sys.argv[2])
        if len(sys.argv) > 2
        else repository / "src" / "stenograf" / "assets" / "icon.ico",
    )
